### ISSUE TITLE
Traceback in the Home Assistant log when iOS actionable notifications are used

### ISSUE THREAD

**Issue by rccoleman** [home-assistant/iOS#1638]
**iOS device model, version and app version**

Model Name: iPhone XS Max
Software Version: 14.5.1
App version: 2021.5

**Home Assistant Core Version**

**Describe the bug**

I created a relatively simple new-format actionable notification and I'm seeing a traceback in the Home Assistant log when I respond with an option and the iOS app doesn't have focus.  The script that triggered the notification and received the response completes successfully and does what it's supposed to do, but I immediately get an error when the script completes, and then another about a minute later

```
2021-05-11 15:02:13 INFO (MainThread) [homeassistant.components.websocket_api.http.connection] [140231289662336] Connection closed by client
2021-05-11 15:02:13 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/aiohttp/web_protocol.py", line 422, in _handle_request
    resp = await self._request_handler(request)
  File "/usr/local/lib/python3.8/site-packages/aiohttp/web_app.py", line 499, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.8/site-packages/aiohttp/web_middlewares.py", line 119, in impl
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 56, in security_filter_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 172, in forwarded_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 18, in request_context_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 74, in ban_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 135, in auth_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 131, in handle
    result = await result
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/http.py", line 43, in get
    return await WebSocketHandler(request.app["hass"], request).async_handle()
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/http.py", line 233, in async_handle
    await self._writer_task
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/http.py", line 78, in _writer
    await self.wsock.send_str(message)
  File "/usr/local/lib/python3.8/site-packages/aiohttp/web_ws.py", line 300, in send_str
    await self._writer.send(data, binary=False, compress=compress)
  File "/usr/local/lib/python3.8/site-packages/aiohttp/http_websocket.py", line 687, in send
    await self._send_frame(message, WSMsgType.TEXT, compress)
  File "/usr/local/lib/python3.8/site-packages/aiohttp/http_websocket.py", line 656, in _send_frame
    await self.protocol._drain_helper()
  File "/usr/local/lib/python3.8/site-packages/aiohttp/base_protocol.py", line 87, in _drain_helper
    await waiter
  File "/usr/local/lib/python3.8/asyncio/selector_events.py", line 935, in _write_ready
    n = self._sock.send(self._buffer)
BrokenPipeError: [Errno 32] Broken pipe
2021-05-11 15:02:13 INFO (MainThread) [homeassistant.components.mobile_app.notify] mobile_app push notification rate limits for Rob’s iPhone XS Max: 19 sent, 500 allowed, 0 errors, resets in 1:57:46
2021-05-11 15:02:13 INFO (MainThread) [homeassistant.components.websocket_api.http.connection] [140231293321424] Connection closed by client

2021-05-11 15:03:08 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/aiohttp/http_websocket.py", line 673, in ping
    await self._send_frame(message, WSMsgType.PING)
  File "/usr/local/lib/python3.8/site-packages/aiohttp/http_websocket.py", line 650, in _send_frame
    self._write(header + message)
  File "/usr/local/lib/python3.8/site-packages/aiohttp/http_websocket.py", line 660, in _write
    raise ConnectionResetError("Cannot write to closing transport")
ConnectionResetError: Cannot write to closing transport
```

I suspect that it's related to the websocket closing when the iOS app displays the notification and then suspends again (closing the websocket), but I can't tell for sure.

**To Reproduce**

Send a notification with an `actions:` block and ensure that the iOS app does not have focus.  See the notification appear on the phone, long-press it to get the options, and select an option.  Note that the errors above are shown in the Home Assistant log, but the script actions complete successfully.

**Expected behavior**

No errors in the Home Assistant log, regardless of whether the iOS app has focus.

**Screenshots**

**Additional context**

**Comment by Petro31** [comment]
Can second this
