### ISSUE TITLE
Blank Pages and freeze + OSError: [Errno 24] Too many open files since the last update 2024.3.0

### ISSUE THREAD

**Issue by ALaDoffe** [home-assistant/iOS#2691]
**iOS device model, version and app version**

Model Name: iPhone 14+ PRO
Software Version: 17.4.1
App version: 2023.3.0

**Home Assistant Core Version**

RPI3B+
BookWorm 32Bits
Python 3.12.2
HA core 2024.3.3 on venv

**Describe the bug**
Hello,

Since the last update, Companion App becomes very laggy on my devices.
When two people are trying to open HA in same time, it'sunusable.
In parrallel I get a lot of error below in HA log.

2024-04-02 13:56:37.948 ERROR (MainThread) [homeassistant] Error doing job: socket.accept() out of system resource
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/asyncio/selector_events.py", line 178, in _accept_connection
  File "/usr/local/lib/python3.12/socket.py", line 295, in accept
OSError: [Errno 24] Too many open files

Indeed, i get :

pi@raspberrypi:~ $ sudo lsof | grep hass | wc -l
80957
pi@raspberrypi:~ $ sudo netstat -nap | grep 8123 | wc -l
851

I have already try to reset the cache frontend but no success.

Thx for help.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by bgoncal** [comment]
How does it behave in iOS Safari browser?

**Comment by ALaDoffe** [comment]
No issue with Safari brower. Only with the App.
After more tests, the issue seems to occur when connected with external access,
No issue when connected with Wifi.

**Comment by bgoncal** [comment]
Did you also try the external URL in iOS Safari?

**Comment by ALaDoffe** [comment]
Yep sir.
The worst is when switching from internal/external URL. Ex when leaving or coming home.
The result of lsof an netstat command grows up.
Closing the app does not release open files and tcp connections.

**Comment by bgoncal** [comment]
Do you want to test if the beta helps your case? There is one specific build that I would like you to check, 2024.4 (612) https://testflight.apple.com/join/1AlPbnLZ

**Comment by ALaDoffe** [comment]
Ok I have just intalled testflight on my phone
Let me know how to do.

**Comment by bgoncal** [comment]
https://github.com/home-assistant/iOS/assets/5808343/900bad05-7508-4ae7-8efe-5a59017bee81

After you see home assistant in testflight app you can navigate as I did in this video and find 2024.4 612

**Comment by ALaDoffe** [comment]
Test flight Ask me for a code.
My Apple id is not the same as Github.

**Comment by bgoncal** [comment]
Open this link again: https://testflight.apple.com/join/1AlPbnLZ then tap to redeem

**Comment by ALaDoffe** [comment]
This beta seems to work like a charm.
No more huge open files or tcp connection.

**Comment by bgoncal** [comment]
Im glad to know 🎉

**Comment by ALaDoffe** [comment]
When this beta will be release to update the rest of the family ?

**Comment by bgoncal** [comment]
Usually in the end of each month, but since it looks like this update is very relevant for several people having similar issues I may create an early release, for now I'll let the beta run a little more to see if no issues are introduced
