### ISSUE TITLE
Control Center control not activating Scripts

### ISSUE THREAD

**Issue by ARandomGitHubUser** [home-assistant/iOS#3010]
**iOS device model, version and app version**

Model Name: iPhone 12
Software Version: iOS 18 (22A3354)
App version: 2024.9

**Home Assistant Core Version**

Core 2024.9.1
Supervisor 2024.09.1
Operating System 13.1
Frontend 20240906.0

**Describe the bug**
Script control center action does not work. Home Assistant logs show an error.

**To Reproduce**
1. Create a script in Home Assistant
2. Add a new script trigger to the iOS control center and select the new script
3. Press the new button in control center
4. Script is not executed, error message in HA logs

**Expected behavior**
The script is executed.

**Additional context**
In Home Assistant log:
```py
2024-09-16 18:24:31.290 ERROR (MainThread) [homeassistant.components.mobile_app.webhook] Error when calling service during mobile_app webhook (device name: <redacted>): Action script.<redacted>-ios_control_center_test not found
2024-09-16 18:24:31.290 ERROR (MainThread) [homeassistant.components.webhook] Error processing webhook <redacted>
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/mobile_app/webhook.py", line 283, in webhook_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 2694, in async_call
    raise ServiceNotFound(domain, service) from None
homeassistant.exceptions.ServiceNotFound: Action script.<redacted>-ios_control_center_test not found

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/webhook/__init__.py", line 192, in async_handle_webhook
    response: Response | None = await webhook["handler"](hass, webhook_id, request)
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/mobile_app/webhook.py", line 265, in handle_webhook
    return await asyncio.shield(
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/mobile_app/webhook.py", line 175, in validate_and_run
    return await func(hass, config_entry, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/mobile_app/webhook.py", line 299, in webhook_call_service
    raise HTTPBadRequest from ex
aiohttp.web_exceptions.HTTPBadRequest: Bad Request
```

**Comment by bgoncal** [comment]
Thanks for reporting, fix coming!
