### ISSUE TITLE
Scripts from widgets do not work after update to 2024.9

### ISSUE THREAD

**Issue by vladbaja** [home-assistant/iOS#3013]
Model Name: iPhone 15
Software Version: 18 (but was also reproduced before update, so on 17.6.1)
App version: 2024.9.1

**Home Assistant Core Version**
2024.9.1

**Describe the bug**
The buttons on my desktop widgets worked until last Home Assistant update. After that, the widget flicker after clicking any button that points to a script.
I tried reinstalling the phone app, the home assistant server (I have it running in Docker), and upgrade iOS to latest today.

**To Reproduce**
Create some scripts. Create widget on iPhone's desktop to run the scripts. Press a button on the widget. The widget flickers and that's all.

**Expected behavior**
The script is run.

**Screenshots**
I found some logs:

Logger: homeassistant.components.mobile_app.webhook
Source: components/mobile_app/webhook.py:291
integration: Mobile App
First occurred: 10:15:38 PM (2 occurrences)
Last logged: 10:15:38 PM

Error when calling service during mobile_app webhook (device name: Vlad): Action script.2da17a4e3b4a4144917a71f699adf80d-priza_1_min not found

and

Logger: homeassistant.components.webhook
Source: components/webhook/init.py:192
integration: Webhook ()
First occurred: 10:15:38 PM (2 occurrences)
Last logged: 10:15:38 PM

Error processing webhook 855a4d99d03cba3cac8d039f97f6a93b0b733c50149dbf6e99553f91f48d5ce6

Traceback (most recent call last): File "/usr/src/homeassistant/homeassistant/components/mobile_app/webhook.py", line 283, in webhook_call_service await hass.services.async_call( File "/usr/src/homeassistant/homeassistant/core.py", line 2694, in async_call raise ServiceNotFound(domain, service) from None homeassistant.exceptions.ServiceNotFound: Action script.2da17a4e3b4a4144917a71f699adf80d-priza_1_min not found The above exception was the direct cause of the following exception: Traceback (most recent call last): File "/usr/src/homeassistant/homeassistant/components/webhook/init.py", line 192, in async_handle_webhook response: Response | None = await webhook["handler"](hass, webhook_id, request) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/src/homeassistant/homeassistant/components/mobile_app/webhook.py", line 265, in handle_webhook return await asyncio.shield( ^^^^^^^^^^^^^^^^^^^^^ File "/usr/src/homeassistant/homeassistant/components/mobile_app/webhook.py", line 175, in validate_and_run return await func(hass, config_entry, data) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/src/homeassistant/homeassistant/components/mobile_app/webhook.py", line 299, in webhook_call_service raise HTTPBadRequest from ex aiohttp.web_exceptions.HTTPBadRequest: Bad Request

**Additional context**
I also posted in another repo: https://github.com/home-assistant/frontend/issues/21999

**Comment by bgoncal** [comment]
Fix coming in app v 2024.9.1, currently under Apple's review

**Comment by FuJuntao** [comment]
Thanks, upgrading to the latest fixed mine.

**Comment by bgoncal** [comment]
Happy to hear that, apologies for the inconvenience

**Comment by vladbaja** [comment]
Just validated in 2024.9.1.

**Comment by asci** [comment]
Is it broken again?

**Comment by bgoncal** [comment]
I havent receive reports about it @asci , which version are you running and happening exactly?
