### ISSUE TITLE
`Error handling message` logged by HA since latest update

### ISSUE THREAD

**Issue by erkr** [home-assistant/iOS#3199]
**iOS device model, version and app version**

Model Name: iPhone 14
Software Version: 18.1.1
App version: 2024.978

**Home Assistant Core Version**
2024.11.3

**Describe the bug**
I have dozens of `Error handling message` logged per hour related to the iOS app

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

``` 
Logger: homeassistant.components.websocket_api.http.connection
Source: components/assist_pipeline/pipeline.py:1445
integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 23:25:49 (6 occurrences)
Last logged: 23:39:00

[546883800944] Error handling message: Unknown error (unknown_error) Eric from 192.168.178.20 (Home Assistant/2024.11 (io.robbie.HomeAssistant; build:2024.978; iOS 18.1.1))
[546881911776] Error handling message: Unknown error (unknown_error) Eric from 192.168.178.20 (Home Assistant/2024.11 (io.robbie.HomeAssistant; build:2024.978; iOS 18.1.1))
[546886191280] Error handling message: Unknown error (unknown_error) Eric from 192.168.178.20 (Home Assistant/2024.11 (io.robbie.HomeAssistant; build:2024.978; iOS 18.1.1))
[546881901264] Error handling message: Unknown error (unknown_error) Eric from 192.168.178.20 (Home Assistant/2024.11 (io.robbie.HomeAssistant; build:2024.978; iOS 18.1.1))
[546851924160] Error handling message: Unknown error (unknown_error) Eric from 192.168.178.20 (Home Assistant/2024.11 (io.robbie.HomeAssistant; build:2024.978; iOS 18.1.1))
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/decorators.py", line 28, in _handle_async_response
    await func(hass, connection, msg)
  File "/usr/src/homeassistant/homeassistant/components/assist_pipeline/websocket_api.py", line 242, in websocket_run
    await pipeline_input.validate()
  File "/usr/src/homeassistant/homeassistant/components/assist_pipeline/pipeline.py", line 1445, in validate
    raise PipelineRunValidationError(
homeassistant.components.assist_pipeline.pipeline.PipelineRunValidationError: the pipeline does not support speech-to-text
```

**Comment by erkr** [comment]
I also get these errors now and then:

``` 
Logger: homeassistant.components.websocket_api.http.connection
Source: components/assist_pipeline/pipeline.py:1445
integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 09:54:47 (2 occurrences)
Last logged: 09:59:50

[547340560864] Error handling message: Unknown error (unknown_error) Eric Kreuwels from 192.168.178.20 (Home Assistant/2024.11 (io.robbie.HomeAssistant; build:2024.978; iOS 18.1.1))
[546818281760] Error handling message: Unknown error (unknown_error) Eric Kreuwels from 192.168.178.20 (Home Assistant/2024.11 (io.robbie.HomeAssistant; build:2024.978; iOS 18.1.1))
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/decorators.py", line 28, in _handle_async_response
    await func(hass, connection, msg)
  File "/usr/src/homeassistant/homeassistant/components/assist_pipeline/websocket_api.py", line 242, in websocket_run
    await pipeline_input.validate()
  File "/usr/src/homeassistant/homeassistant/components/assist_pipeline/pipeline.py", line 1445, in validate
    raise PipelineRunValidationError(
homeassistant.components.assist_pipeline.pipeline.PipelineRunValidationError: the pipeline does not support speech-to-text
```

**Comment by bgoncal** [comment]
Are you having issues using Assist on iOS app? (asking based on your logs)

**Comment by bgoncal** [comment]
That's very weird, I'll see if I can find the root cause

**Comment by erkr** [comment]
Just installed the release candidate and will check if they still occure

**Comment by erkr** [comment]
Don't see them anymore 👌

**Comment by kstuken** [comment]
I continue having this error

```
2025-01-26 10:05:09.652 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [546917429120] Error handling message: Unknown error (unknown_error) Kai from 192.168.xxx.xx (Home Assistant/2024.12.2 (io.robbie.HomeAssistant; build:2024.1058; iPadOS 18.1.1))
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/decorators.py", line 28, in _handle_async_response
    await func(hass, connection, msg)
  File "/usr/src/homeassistant/homeassistant/components/assist_pipeline/websocket_api.py", line 242, in websocket_run
    await pipeline_input.validate()
  File "/usr/src/homeassistant/homeassistant/components/assist_pipeline/pipeline.py", line 1524, in validate
    raise PipelineRunValidationError(
        "the pipeline does not support speech-to-text"
    )
homeassistant.components.assist_pipeline.pipeline.PipelineRunValidationError: the pipeline does not support speech-to-text
```

I pops up quite a lot when I work with the iPad app. (and weirdly enough, only the iPad app, not the iPhone app).

Mine is a relatively fresh install (started with yellow and HA 2024.12) and I do not use any voice assistance nor have I tried it out.

I am a bit confused about the "Home Assistant/2024.12.2" in the log, as according to Settings / About I am on 2025.1.4 (Core) and 2024.12.3 (Supervisor).

Should I open a new issue?

**Comment by bgoncal** [comment]
Please open a new issue, but if this is not the version installed in your iPad then it is coming from somewhere else, do you have another iPad or someone else’s with access to your instance? 

You can also configure speech to text to see if this goes away or keeps happening, just so we know where is it coming from

**Comment by kstuken** [comment]
Thank you, I have raised issue https://github.com/home-assistant/iOS/issues/3356

I double-checked, it is the correct iPad (there is only one iPad in our household running the app at the moment).
I will consider looking into speech to text, but as I am new to HA (currently migrating from OpenHAB), there is currently still a steep learning curve for a lot of things...
